name: Deploy to WordPress.org

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build plugin
        run: |
          chmod +x build.sh
          ./build.sh

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: datasheet-pdf-generator-for-woocommerce
          BUILD_DIR: dist/datasheet-pdf-generator-for-woocommerce
          ASSETS_DIR: .wordpress-org
